# Site settings
title: CrewGuru
description: Crew guru prototype
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.crewguru.com"

# Build settings
markdown: kramdown
port: 8000
sass:
  sass_dir: assets/css
  style: :nested